export const FETCH_POSTS_STARTED = 'FETCH_POSTS_STARTED'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED'

export const FETCH_POST_STARTED = 'FETCH_POST_STARTED'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED'

export const FETCH_COMMENTS_STARTED = 'FETCH_COMMENTS_STARTED'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED'

export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const FILTER_POSTS_BY_USER_ID = 'FILTER_POSTS_BY_USER_ID'

export const DELETE_POST_STARTED = 'DELETE_POST_STARTED'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED'
